# .github/workflows/create-feature-branch.yml
name: Create feature branch from canary

on:
  workflow_dispatch:
    inputs:
      feature_name:
        description: "Name of the feature (branch will be feature/<name>)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history needed for branch creation

      - name: Verify 'canary' branch exists on remote
        run: |
          if ! git ls-remote --exit-code origin canary >/dev/null 2>&1; then
            echo "Error: 'canary' branch does not exist on remote. Exiting."
            exit 1
          fi

      - name: Create feature branch from canary
        run: |
          # Raw input from user
          RAW_INPUT="${{ github.event.inputs.feature_name }}"

          # Sanitise: lowercase, collapse invalid chars to '-', then trim leading/trailing '-'
          SAFE_NAME=$(echo "$RAW_INPUT" \
            | tr '[:upper:]' '[:lower:]' \
            | tr -cs 'a-z0-9._-' '-' \
            | sed 's/^-*//; s/-*$//')

          if [ -z "$SAFE_NAME" ]; then
            echo "Error: feature name becomes empty after sanitisation. Please use letters/numbers/dot/underscore/hyphen."
            exit 1
          fi

          FEATURE_BRANCH="feature/$SAFE_NAME"
          echo "Creating branch: $FEATURE_BRANCH"

          # Ensure local canary is up to date
          git fetch origin canary
          git checkout -B canary origin/canary
          git pull --ff-only origin canary

          # Create and push the feature branch
          git checkout -b "$FEATURE_BRANCH"
          git push origin "$FEATURE_BRANCH"
