name: Generate APT Packages Metadata

on:
  workflow_dispatch:  # This makes it manual (run from Actions tab)

jobs:
  build-packages-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages and Packages.gz
        run: |
          cd docs
          dpkg-scanpackages --multiversion dists/stable/main/binary-all /dev/null | tee dists/stable/main/binary-all/Packages | gzip -9 > dists/stable/main/binary-all/Packages.gz

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/dists/stable/main/binary-all/Packages docs/dists/stable/main/binary-all/Packages.gz
          git commit -m "Auto-generate Packages and Packages.gz [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
